export default {
  saveIcon: require('./saveIcon.png'),
  shareIcon: require('./shareIcon.png'),
  printIcon: require('./printIcon.png'),
  downloadIcon: require('./downloadIcon.png'),
  headingIcon: require('./heading.png'),
  tableIcon: require('./table.png'),
  textIcon: require('./text.png'),
  checkboxIcon: require('./checkbox.png'),
  coverPageIcon: require('./coverpage.png'),
  datePickerIcon: require('./datepicker.png'),
  dropDownIcon: require('./dropdown.png'),
  imageIcon: require('./image.png'),
  pageBreakIcon: require('./pagebreak.png'),
  videoIcon: require('./video.png'),
  ratingIcon: require('./rate.png'),
  publishIcon: require('./publish.png'),
  paragraphIcon: require('./paragraphIcon.png'),
  footerIcon: require('./footer.png'),
  signatureIcon: require('./signature.png'),
  dividerIcon: require('./divider.png'),
  logoIcon: require('./logo.png'),
  cover1: require('./cover-1.jpg'),
  cover2: require('./cover-2.jpg'),
  cover1Preview: require('./cover-1-preview.jpg'),
  cover2Preview: require('./cover-2-preview.jpg')
};
